# GitHub README Terminal Configuration

[general]
# Terminal dimensions
width = 800
height = 600
xpad = 10
ypad = 10

[font]
# Font settings
size = 16
file_path = "default"

[output]
# Output settings
gif_name = "terminal.gif"
fps = 10

[cursor]
# Cursor settings
blink = true
style = "block"