# GitHub README Terminal Configuration

[general]
# Terminal dimensions
width = 800
height = 400
xpad = 10
ypad = 10

[font]
# Font settings
size = 14
family = "JetBrains Mono"

[colors]
# Gruvbox Dark color scheme for a retro terminal look
scheme = "gruvbox_dark"

[cursor]
# Cursor behavior
blink = true
style = "block"

[animation]
# Animation settings
typing_speed = 5
frame_duration = 100
loop_count = 0

[output]
# Output settings
file_name = "terminal.gif"
optimize = true